# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testReadQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Read_QR(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(372, 304)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 351, 211))
        self.image_label.setStyleSheet("background-color: white\n")
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.cancel_btn = QtWidgets.QPushButton(Form)
        self.cancel_btn.setGeometry(QtCore.QRect(20, 230, 101, 61))
        self.cancel_btn.setObjectName("cancel_btn")
        self.scan_btn = QtWidgets.QPushButton(Form)
        self.scan_btn.setGeometry(QtCore.QRect(130, 230, 221, 61))
        self.scan_btn.setObjectName("scan_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))
        self.scan_btn.setText(_translate("Form", "Scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Read_QR()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
